[package]
name = "axplat-loongarch64-qemu-virt"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[features]
fp-simd = ["axcpu/fp-simd"]
irq = ["axplat/irq"]
rtc = ["dep:chrono"]
smp = ["axplat/smp", "kspin/smp"]

[dependencies]
kspin = "0.1"
log = "0.4"
lazyinit = "0.2"
memory_addr = "0.3"
loongArch64 = "0.2.4"
ns16550a = "0.5.0"
page_table_entry = "0.5"
chrono = { version = "0.4", default-features = false, optional = true }

axconfig-macros = "0.2"
axcpu = { workspace = true }
axplat = { workspace = true }
