name: Test

on: [push, pull_request]

env:
  qemu-version: 9.2.4

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, clippy, llvm-tools
      - name: Clippy
        run: cargo clippy -p cargo-axplat
      - name: Build
        run: cargo build -p cargo-axplat
      - name: Create and test new axplat project from template
        run: |
          cargo run -p cargo-axplat -- axplat new /tmp/axplat-test --axplat-path "${{ github.workspace }}/axplat"
          cd /tmp/axplat-test
          cargo check

  examples:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64, riscv64, loongarch64, arm]
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, clippy, llvm-tools
          targets: x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none-softfloat, loongarch64-unknown-none-softfloat, armv7a-none-eabi
      - name: Install cargo-binutils
        run: cargo install cargo-binutils
      - uses: arceos-org/setup-qemu@v1
        with:
          version: ${{ env.qemu-version }}
          arch_list: x86_64,aarch64,riscv64,loongarch64,arm
      - name: Clippy
        run: |
          make -C examples/hello-kernel ARCH=${{ matrix.arch }} clippy
          make -C examples/irq-kernel ARCH=${{ matrix.arch }} clippy
          make -C examples/smp-kernel ARCH=${{ matrix.arch }} clippy
      - name: Build
        run: |
          make -C examples/hello-kernel ARCH=${{ matrix.arch }}
          make -C examples/irq-kernel ARCH=${{ matrix.arch }}
          make -C examples/smp-kernel ARCH=${{ matrix.arch }} SMP=4
      - name: Test
        run: |
          make -C examples/hello-kernel ARCH=${{ matrix.arch }} run
          make -C examples/irq-kernel ARCH=${{ matrix.arch }} run
          make -C examples/smp-kernel ARCH=${{ matrix.arch }} SMP=4 run
